### ISSUE TITLE
Is Y-Axis Rotation possible

### ISSUE THREAD

**Issue by nux1111** [huanngzh/ComfyUI-MVAdapter#11]
Thanks for this node. I was wondering if rotation on Y-axis is possible

**Comment by prozacgod** [comment]
This might be stupid, but ... have you considered just rotating the image, I'm curious if that works.

**Comment by huanngzh** [comment]
> Thanks for this node. I was wondering if rotation on Y-axis is possible

Hi, is this what you mean?

![output_1](https://github.com/user-attachments/assets/0e9d5f32-dd36-4d2c-9101-25f42efcb9aa)
![output_2](https://github.com/user-attachments/assets/c40ef8bb-6d73-4f5c-85b6-e3b8d1ba27c1)
![output_2](https://github.com/user-attachments/assets/aca1f8b1-6712-40af-b506-2ca0cb8c2123)
![output_3](https://github.com/user-attachments/assets/50488eb7-6787-4fea-bfa3-96eec2e5b745)

**Comment by nux1111** [comment]
> This might be stupid, but ... have you considered just rotating the image, I'm curious if that works.

Yeah, I tried but since the model didn't really understand what it was seeing, it failed.

**Comment by nux1111** [comment]
> > Thanks for this node. I was wondering if rotation on Y-axis is possible
> 
> Hi, is this what you mean?
> 
> ![output_1](https://private-user-images.githubusercontent.com/78398294/394094645-0e9d5f32-dd36-4d2c-9101-25f42efcb9aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDI1NzMsIm5iZiI6MTczNDAwMjI3MywicGF0aCI6Ii83ODM5ODI5NC8zOTQwOTQ2NDUtMGU5ZDVmMzItZGQzNi00ZDJjLTkxMDEtMjVmNDJlZmNiOWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDExMTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ODk5NDNiZDA3MjRlODRlMmE4OTE5Mzc5ZjE0ZjlmY2I4OTc5NGVjNWM1ZjFiZWQwODYxMWUyNTc1OTJlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RZpA5Jowxf6vKE_ki2jQwwnUt9ZrDfVhT4VcPcTKZ74) ![output_2](https://private-user-images.githubusercontent.com/78398294/394094662-c40ef8bb-6d73-4f5c-85b6-e3b8d1ba27c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDI1NzMsIm5iZiI6MTczNDAwMjI3MywicGF0aCI6Ii83ODM5ODI5NC8zOTQwOTQ2NjItYzQwZWY4YmItNmQ3My00ZjVjLTg1YjYtZTNiOGQxYmEyN2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDExMTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYTgzYTc5OGM3ZmNjMTJlODI5MmVjNWY2MDU2NTU2MDdhZWY5NjY0OTBjNmUyNjYyYjYyYmZkMTc3ODZhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fyuHu9TKBi1WauXDvtwFig5osovrM5b-pt0x2gTSi9g) ![output_2](https://private-user-images.githubusercontent.com/78398294/394094677-aca1f8b1-6712-40af-b506-2ca0cb8c2123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDI1NzMsIm5iZiI6MTczNDAwMjI3MywicGF0aCI6Ii83ODM5ODI5NC8zOTQwOTQ2NzctYWNhMWY4YjEtNjcxMi00MGFmLWI1MDYtMmNhMGNiOGMyMTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDExMTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTQ1NTZhNzQ2ZWFhZjI0ZmZhMWQ4Nzc3YzdlYzE1NzI0ZmU2MjcxNWZhYTk0ZTcwYzc4NmZjNWY4MThkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xts_Dn7YTSTXfH5NSmlwVL1Ha_wDM0aa-ugu51P6MpI) ![output_3](https://private-user-images.githubusercontent.com/78398294/394094704-50488eb7-6787-4fea-bfa3-96eec2e5b745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDI1NzMsIm5iZiI6MTczNDAwMjI3MywicGF0aCI6Ii83ODM5ODI5NC8zOTQwOTQ3MDQtNTA0ODhlYjctNjc4Ny00ZmVhLWJmYTMtOTZlZWMyZTViNzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDExMTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YzEzNjdlMjk3MzVmOGFiZjM4ZjZlMzI5ZGFjNmQ0OTQ0YTUzMmEzMzA5YTI0ZjM1YmVkODRjYjVkZGQ4MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kzQz-Ul5GOSDZeenirxqrqMp10tNApZy7lmILprdyr8)

Yes, including maybe an isometrick perspective. Thanks for the reply.

**Comment by prozacgod** [comment]
It's kind of wild you can even generate those, given that the underlying models often struggle generating creatures or statues or whatever in upside down or alternative orientations. They always get a little wonky.

**Comment by huanngzh** [comment]
> It's kind of wild you can even generate those, given that the underlying models often struggle generating creatures or statues or whatever in upside down or alternative orientations. They always get a little wonky.

Yep, cant agree more.

**Comment by huanngzh** [comment]
The currently released model does not support the generation of relatively free perspective images. Once it is supported, we will adjust the nodes.
