### ISSUE TITLE
num_views is unused

### ISSUE THREAD

**Issue by civen-cn** [huanngzh/ComfyUI-MVAdapter#13]
in code utils.py line 290, the elevation_deg=[0, 0, 0, 0, 0, 0], if change the input num_views, will be error.

**Comment by huanngzh** [comment]
Hi, our currently open-source model is only trained on 6 perspectives with an elevation of 0, so it works well only for generating images from these 6 views. Our arbitrary view generation model is not yet publicly available. We do not recommend changing `num_views`.

**Comment by 1blackbar** [comment]
Will you train on 8 views in the future ? with backside views ?
