### ISSUE TITLE
Black image

### ISSUE THREAD

**Issue by meta10110** [huanngzh/ComfyUI-MVAdapter#14]
![image](https://github.com/user-attachments/assets/684e1459-1808-4e74-8f7c-b85fabecd7d8)

terminal:

E:\AIGC\ComfyUI\venv\Lib\site-packages\diffusers\image_processor.py:147: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")

**Comment by huanngzh** [comment]
Hi, please make sure to use the [sdxl-vae-fp16-fix](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix) as the VAE. Or set the `upcast_fp32` in the LDM VAE Loader node to `True` if your GPU memory is enough.

**Comment by huanngzh** [comment]
Thanks for your issues. I have made the `upcast_fp32` to `True` by default to avoid the errors.
