### ISSUE TITLE
cross_attention_kwargs ['mv_scale'] are not expected

### ISSUE THREAD

**Issue by freshwind-bit** [huanngzh/ComfyUI-MVAdapter#15]
ComfyUI: v0.3.7 (2024-12-04), VRAM=22GB
t2mv_sdxl_ldm.json
After all the files have downloaded, there is a massive amount of messages in the terminal:
**cross_attention_kwargs ['mv_scale'] are not expected by AttnProcessor2_0 and will be ignored.**

![cross_attention_kwargs_t2mv](https://github.com/user-attachments/assets/4a7111f3-2c4f-412d-97a4-aa50ea9a679a)

**Comment by huanngzh** [comment]
Refer to #14

**Comment by freshwind-bit** [comment]
In the link you provided, you suggest doing what I have already done at the beginning, judging by the screenshot I attached.

**Comment by huanngzh** [comment]
Sorry... Could you provide more outputs in the terminal? Your provided `cross_attention_kwargs ['mv_scale'] are not expected by AttnProcessor2_0 and will be ignored.` will not affect the results in fact.

**Comment by freshwind-bit** [comment]
Certainly! Now I have reinstalled the extension and the output of your t2mv_sdxl_ldm.json has images. But the terminal with the CUI is massively filled with the same quoted message. Yes, this message does not affect the result now, but it clutters up the terminal. Is it possible to remove it from the standard output when running ComfyUI with default arguments? 
I am attaching the log.
[comfyui_log.zip](https://github.com/user-attachments/files/18087007/comfyui_log.zip)

**Comment by huanngzh** [comment]
Working on it! #1
