### ISSUE TITLE
输出图像为黑色图像，使用的是官方工作流

### ISSUE THREAD

**Issue by zk495539792** [huanngzh/ComfyUI-MVAdapter#20]
![Uploading 1733913080698.jpg…]()

**Comment by huanngzh** [comment]
Hi, I cant see your uploaded screenshot. Btw, we refer you to similar issues #14 or #15.

**Comment by zk495539792** [comment]
> Hi, I cant see your uploaded screenshot. Btw, we refer you to similar issues #14 or #15.嗨，我看不到您上传的屏幕截图。顺便说一句，我们建议您参考类似的问题 #14 或 #15 .

好的，我将尝试
