### ISSUE TITLE
Generate Blank images all black!?

### ISSUE THREAD

**Issue by merecesarchviz** [huanngzh/ComfyUI-MVAdapter#21]
Hi

I installed the addon, it run all well without errors but the output is always a black image!! I change the sdxl models etc and I always get the same result! any idea?

![errer](https://github.com/user-attachments/assets/9ef37467-c260-4019-a662-f7915e0fa7c6)

**Comment by huanngzh** [comment]
Hi, please make sure to use the [sdxl-vae-fp16-fix](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix) as the VAE. Or set the `upcast_fp32` in the LDM VAE Loader node to `True` if your GPU memory is enough.

**Comment by merecesarchviz** [comment]
> Hi, please make sure to use the [sdxl-vae-fp16-fix](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix) as the VAE. Or set the `upcast_fp32` in the LDM VAE Loader node to `True` if your GPU memory is enough.

Yes it solve my issue! downloading that sdxl vae fix, thank you for the advise.
