### ISSUE TITLE
Images come out black

### ISSUE THREAD

**Issue by yovsac** [huanngzh/ComfyUI-MVAdapter#22]
Hello,

when trying to use the t2mv sdxl ldm Lora. I get black images as output. Why is that?

![Untitled-1](https://github.com/user-attachments/assets/8afe2ed6-1c7e-4b29-b2fa-41cbe120c17a)

**Comment by huanngzh** [comment]
Hi, could you try the solution in #21 ?

**Comment by yovsac** [comment]
Yes, that worked thank you!
