### ISSUE TITLE
plz add vae decode tile or vae decode list in mv sampler

### ISSUE THREAD

**Issue by xueqing0622** [huanngzh/ComfyUI-MVAdapter#26]
plz add vae decode tile or vae decode list in mv sampler
it is easy to out of memory after render all sampler

Loading pipeline components...:  14%|███████▍                                            | 1/7 [00:00<00:00,  6.16it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel:
 ['text_model.embeddings.position_ids']
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:01<00:00,  5.24it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [01:05<00:00,  1.32s/it]
!!! Exception during processing !!! Allocation on device

**Comment by huanngzh** [comment]
Updated!
![image](https://github.com/user-attachments/assets/6853a112-0aa0-40fb-b00f-bbfcd70f8de0)

**Comment by xueqing0622** [comment]
after update always  torch.OutOfMemoryError: Allocation on device, before run diffuser mv sampler, ever worse
Loading pipeline components...:   0%|                                                            | 0/7 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel:
 ['text_model.embeddings.position_ids']
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:00<00:00, 10.71it/s]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MVAdapter\nodes.py", line 463, in sample
    images = pipeline(
             ^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MVAdapter\mvadapter\pipelines\pipeline_mvadapter_i2mv_sdxl.py", line 646, in __call__
    ref_hidden_states = {
                        ^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MVAdapter\mvadapter\pipelines\pipeline_mvadapter_i2mv_sdxl.py", line 647, in <dictcomp>
    k: torch.cat([torch.zeros_like(v), v], dim=0)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

**Comment by huanngzh** [comment]
Could you show the GPU memory of the device you are running MV-Adapter on? As we show in the README, since SDXL is used as the base model, it requires about 13G to 14G GPU memory.

**Comment by xueqing0622** [comment]
Tested it today, it was because my input image was too big, to be the same size as the output image there is no problem.

**Comment by xueqing0622** [comment]
my vram 12G , after update the vae tile, can run 624 pixels , thx your update.
