### ISSUE TITLE
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same

### ISSUE THREAD

**Issue by coddz** [huanngzh/ComfyUI-MVAdapter#29]
![image](https://github.com/user-attachments/assets/b64f1126-0baa-4272-bc9f-117814d80c99)
i2mv_sdxl_ldm.json and i2mv_sdxl_ldm_lora.json raise issue like this: 

!!! Exception during processing !!! Input type (struct c10::Half) and bias type (float) should be the same
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\nodes.py", line 463, in sample
    images = pipeline(
             ^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\mvadapter\pipelines\pipeline_mvadapter_i2mv_sdxl.py", line 673, in __call__
    adapter_state = self.cond_encoder(control_image_feature)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\adapter.py", line 274, in forward
    return self.adapter(x)
           ^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\adapter.py", line 380, in forward
    x = self.conv_in(x)
        ^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same

**Comment by coddz** [comment]
the custom node was updated to the newest version.

python 3.12 torch 2.5.1+cu124

**Comment by coddz** [comment]
![image](https://github.com/user-attachments/assets/6cb7b8d0-3b81-400b-8b79-9450720edc7e)
If load_mvadapter=true, the error message is below( the workflow i2mv_sdxl_ldm.json was right some day before):

!!! Exception during processing !!! 'down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q.weight'
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\nodes.py", line 310, in makeup_pipeline
    pipeline.init_custom_adapter(num_views=num_views)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\mvadapter\loaders\custom_adapter.py", line 14, in init_custom_adapter
    self._init_custom_adapter(*args, **kwargs)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\mvadapter\pipelines\pipeline_mvadapter_i2mv_sdxl.py", line 934, in _init_custom_adapter
    state_dict[key] = state_dict[compatible_key].clone()
                      ~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q.weight'

**Comment by huanngzh** [comment]
> If load_mvadapter=true, the error message is below( the workflow i2mv_sdxl_ldm.json was right some day before):

Have you made any updates, such as reinstalling the Python environment package?

**Comment by coddz** [comment]
comfyui and custom nodes are upated sometimes. Our comfyui-MVAdapter are updated with the github.

**Comment by coddz** [comment]
python env has not updated when checking through 'pip install -r requirements.txt':
F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter>f:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torch>=2.1.1 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (2.5.1+cu124)
Requirement already satisfied: torchvision>=0.16.1 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (0.20.1+cu124)
Requirement already satisfied: diffusers>=0.31.0 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 3)) (0.31.0)
Requirement already satisfied: transformers>=4.46.3 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 4)) (4.47.0)
Requirement already satisfied: peft in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 5)) (0.13.2)
Requirement already satisfied: numpy>=1.26.2 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 6)) (1.26.3)
Requirement already satisfied: huggingface_hub>=0.24.6 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 7)) (0.27.0)
Requirement already satisfied: accelerate>=1.1.1 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 8)) (1.2.1)
Requirement already satisfied: opencv-python in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 9)) (4.10.0.84)
Requirement already satisfied: safetensors in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 10)) (0.4.5)
Requirement already satisfied: pillow in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 11)) (10.4.0)
Requirement already satisfied: omegaconf in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 12)) (2.3.0)
Requirement already satisfied: trimesh in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 13)) (4.5.2)
Requirement already satisfied: einops in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 14)) (0.8.0)
Requirement already satisfied: timm in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 15)) (1.0.12)
Requirement already satisfied: kornia in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 16)) (0.7.4)
Requirement already satisfied: scikit-image in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 17)) (0.24.0)
Requirement already satisfied: filelock in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=2.1.1->-r requirements.txt (line 1)) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=2.1.1->-r requirements.txt (line 1)) (4.12.2)
Requirement already satisfied: networkx in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=2.1.1->-r requirements.txt (line 1)) (3.4.2)
Requirement already satisfied: jinja2 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=2.1.1->-r requirements.txt (line 1)) (3.1.4)
Requirement already satisfied: fsspec in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=2.1.1->-r requirements.txt (line 1)) (2024.9.0)
Requirement already satisfied: setuptools in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=2.1.1->-r requirements.txt (line 1)) (75.6.0)
Requirement already satisfied: sympy==1.13.1 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=2.1.1->-r requirements.txt (line 1)) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy==1.13.1->torch>=2.1.1->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: importlib-metadata in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.31.0->-r requirements.txt (line 3)) (8.5.0)
Requirement already satisfied: regex!=2019.12.17 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.31.0->-r requirements.txt (line 3)) (2024.11.6)
Requirement already satisfied: requests in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers>=0.31.0->-r requirements.txt (line 3)) (2.32.3)
Requirement already satisfied: packaging>=20.0 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers>=4.46.3->-r requirements.txt (line 4)) (24.2)
Requirement already satisfied: pyyaml>=5.1 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers>=4.46.3->-r requirements.txt (line 4)) (6.0.2)
Requirement already satisfied: tokenizers<0.22,>=0.21 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers>=4.46.3->-r requirements.txt (line 4)) (0.21.0)
Requirement already satisfied: tqdm>=4.27 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers>=4.46.3->-r requirements.txt (line 4)) (4.67.0)
Requirement already satisfied: psutil in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from peft->-r requirements.txt (line 5)) (6.1.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from omegaconf->-r requirements.txt (line 12)) (4.9.3)
Requirement already satisfied: kornia-rs>=0.1.0 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from kornia->-r requirements.txt (line 16)) (0.1.7)
Requirement already satisfied: scipy>=1.9 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r requirements.txt (line 17)) (1.14.1)
Requirement already satisfied: imageio>=2.33 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r requirements.txt (line 17)) (2.36.0)
Requirement already satisfied: tifffile>=2022.8.12 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r requirements.txt (line 17)) (2024.9.20)
Requirement already satisfied: lazy-loader>=0.4 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r requirements.txt (line 17)) (0.4)
Requirement already satisfied: colorama in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.27->transformers>=4.46.3->-r requirements.txt (line 4)) (0.4.6)
Requirement already satisfied: zipp>=3.20 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from importlib-metadata->diffusers>=0.31.0->-r requirements.txt (line 3)) (3.21.0)
Requirement already satisfied: MarkupSafe>=2.0 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=2.1.1->-r requirements.txt (line 1)) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers>=0.31.0->-r requirements.txt (line 3)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers>=0.31.0->-r requirements.txt (line 3)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers>=0.31.0->-r requirements.txt (line 3)) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers>=0.31.0->-r requirements.txt (line 3)) (2024.8.30)

**Comment by coddz** [comment]
i2mv_sdxl_ldm.json works well today, and I can't say why. 

![image](https://github.com/user-attachments/assets/c30586bc-db99-4e38-8308-4af7d23c6594)

**Comment by coddz** [comment]
Maybe xx custom node changed the python env, and yy custom node change the python env back?
