### ISSUE TITLE
Several models were automatically downloaded and all of them were stuffed into the cache space of the C drive

### ISSUE THREAD

**Issue by coddz** [huanngzh/ComfyUI-MVAdapter#3]
C drive is limited, Can the author modify the code to change the model into Comfyui/models?

**Comment by coddz** [comment]
the requirements.txt need checking and changing, for example: 
torch>=2.1.1
torchvision>=0.16.1
diffusers>=0.31.0
transformers>=4.46.3
peft
numpy>=1.26.2
huggingface_hub>=0.24.6
accelerate>=1.1.1

the torch version is too low, may cause a lot of custom nodes failure.

**Comment by coddz** [comment]
the checkpoint(sdxl) and vae(sdxl) of diffusers loader maybe select from the local like ldm, avoid downloading the sdxl base repetitavely.

**Comment by huanngzh** [comment]
Thanks for your suggestions! The above issues have been solved.

Btw, `diffusers` will not download the checkpoints repetitavely due to its cache mechanism. Now the cache dir has been set to `ComfyUI/models/diffusers`.
