### ISSUE TITLE
model loading question

### ISSUE THREAD

**Issue by ricardo-ml** [huanngzh/ComfyUI-MVAdapter#32]
I have already selected the SDXL model, Why does it still automatically download the stable-diffusion-xl-base-1.0 model?

**Comment by huanngzh** [comment]
Are you using ldm pipeline? Could you provide the screenshot? If you use ldm nodes, it will download the config for `stable-diffusion-xl-base-1.0` but not the model weights.

**Comment by ricardo-ml** [comment]
yes, i used ldm pipeline
![3](https://github.com/user-attachments/assets/7f533ffd-b0de-41bf-b076-bff2d72e2477)
![4](https://github.com/user-attachments/assets/2ff93ee8-6a45-485d-9811-0952b451ec71)

**Comment by huanngzh** [comment]
Well, it will download the config for `stable-diffusion-xl-base-1.0` but not the model weights. You can run the following command firstly:

```Bash
export HF_ENDPOINT=https://hf-mirror.com
```

It will help you successfully download the configs for sdxl into the diffusers dir.

**Comment by ricardo-ml** [comment]
OK， thank you so mush
